=== dmgustav/dmgustav.github.io/z656/assignment3/album.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT album (provenance, recording, sleeve)>
<!ELEMENT provenance (label, reclocation, technical, creators+)>
<!ELEMENT label (#PCDATA|original|remaster)* >
<!ATTLIST label id CDATA #IMPLIED >
<!ELEMENT original (#PCDATA) >
<!ELEMENT remaster (#PCDATA) >
<!ATTLIST original id ID #IMPLIED>
<!ATTLIST remaster id ID #IMPLIED >
<!ELEMENT reclocation (studio*, city*)>
<!ATTLIST reclocation id ID #IMPLIED >
<!ELEMENT studio (#PCDATA) >
<!ELEMENT city (globalcord) >
<!ELEMENT globalcord (#PCDATA) >
<!ATTLIST globalcord lat CDATA #REQUIRED >
<!ATTLIST globalcord long CDATA #REQUIRED >
<!ELEMENT technical (media+) >
<!ELEMENT media (#PCDATA) >
<!ATTLIST media type CDATA #IMPLIED >
<!ATTLIST media tracking (full|half|quad) #IMPLIED >
<!ATTLIST media ips (1.875|3.75|7.5|15|30|slow) #IMPLIED >
<!ELEMENT creators (person*, organization*) >
<!ELEMENT person (#PCDATA|role)* >
<!ATTLIST person id CDATA #IMPLIED >
<!ELEMENT role (#PCDATA) >
<!ELEMENT organization (#PCDATA|role)* >
<!ATTLIST organization id CDATA #IMPLIED >
<!ELEMENT recording ANY >
<!ELEMENT sleeve (frontcover?,backcover?) >
<!ELEMENT frontcover (title?, artist*, coverimage?) >
<!ATTLIST frontcover text CDATA #IMPLIED >
<!ELEMENT title (#PCDATA) >
<!ELEMENT artist (person, group) >
<!ELEMENT group (#PCDATA) >
<!ELEMENT coverimage ANY >
<!ATTLIST coverimage href CDATA #IMPLIED >
<!ELEMENT backcover (sidebar*, tracklist, albumcredits, background?) >
<!ATTLIST backcover text CDATA #IMPLIED >
<!ELEMENT sidebar (#PCDATA|specialcharacter)*>
<!ATTLIST sidebar location (left|right) #REQUIRED >
<!ATTLIST sidebar orientation (bottom-top|top-bottom) #REQUIRED >
<!ELEMENT specialcharacter ANY >
<!ATTLIST specialcharacter id CDATA #REQUIRED >
<!ATTLIST specialcharacter href CDATA #IMPLIED >
<!ELEMENT tracklist (song+) >
<!ATTLIST tracklist location (top|center|bottom) #IMPLIED >
<!ATTLIST tracklist alignment (left|center|right) #IMPLIED >
<!ELEMENT song (title, songcredits*) >
<!ATTLIST song track ID #REQUIRED>
<!ELEMENT songcredits (#PCDATA|person|label)*>
<!ELEMENT albumcredits (producers, engineers, remix, vocalbackgrounds, stringarrangement, strings, horns, rhythm, location)>
<!ATTLIST albumcredits location (top|center|bottom) #IMPLIED >
<!ATTLIST albumcredits alignment (left|center|right) #IMPLIED >
<!ELEMENT producers (#PCDATA|person|organization)* >
<!ELEMENT engineers (#PCDATA|person|organization)* >
<!ELEMENT remix (#PCDATA|person|organization)* >
<!ELEMENT vocalbackgrounds (#PCDATA|person|organization)* >
<!ELEMENT stringarrangement (#PCDATA|person|organization)* >
<!ELEMENT strings (#PCDATA|person|organization)* >
<!ELEMENT horns (#PCDATA|person|organization)* >
<!ELEMENT rhythm (#PCDATA|person|organization)* >
<!ELEMENT location (#PCDATA|reclocation)* >
<!ELEMENT background ANY >
<!ELEMENT image EMPTY >
<!ATTLIST image href CDATA #IMPLIED>
<!ATTLIST background href CDATA #IMPLIED >

=== dmgustav/dmgustav.github.io/z656/assignment3/algreen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE album SYSTEM "album.dtd">
<album>
    <provenance>
        <label>
            <original id="bmi">BMI</original>
            <remaster id="hi">Hi Records</remaster>
        </label>
        <reclocation id="RRS"><studio>Royal Recording Studios</studio> <city><globalcord
                    lat="35° 7′ 3″ N" long="89°58′16″W">Memphis,
            TN</globalcord></city></reclocation>
        <technical>
            <media>DVD</media>
            <media type="original" tracking="quad" ips="7.5">ORT</media>
        </technical>
        <creators>
            <person id="A Green">Al Green <role>Lead</role>
                <role>Producer</role>
                <role>Writer</role>
            </person>
            <person id="W Mitchell">Willie Mitchell <role>Producer</role>
                <role >Engineer</role>
                <role >Remix-Engineer</role>
                <role>Writer</role>
            </person>
            <person id="Rhodes1">Rhodes <role>Vocal Backgrounds</role></person>
            <person id="Rhodes2">Rhodes <role>Vocal Backgrounds</role></person>
            <!-- I did a quick search forthe two Rhodes listed here, but I wasn't able find any information. It's probably out there, just not readily avalible through google for someone unfamilier w/ Al Green-->
            <person id="C Chalmers"> Charles Chalmers <role>Vocal Backgrounds</role>
                <!-- I make the assumption that the Chalmers listed in vocal backgrounds is the same Chalmers who did string arrangments -->
                <role>String Arrangement</role>
            </person>
            <person id="J Mitchell">James Mitchell <role>String Arrangement</role>
                <role>Baritone Sax</role>
            </person>
            <person id="W Jackson">Wayne Jackson <role>Trumpet</role></person>
            <person id="A Love">Andrew Love <role>Tenor</role></person>
            <person id="E Logan">Ed Logan<role>Tenor</role></person>
            <person id="J Hole">Jack Hole <role>Trombone</role></person>
            <person id="H Grimes">Howard Grimes<role>Drums, Congas, &amp; Bongo</role></person>
            <person id="A Jackson">Al Jackson <role>Drums, Congas, &amp; Bongo</role></person>
            <person id="L Hodges">Leroy Hodges <role>Bass</role></person>
            <person id="C Hodges">Charles Hodges <role>Organ and Piano</role></person>
            <person id="T Hodges">Teenie Hodges<role>Guitar</role></person>
            <person id="A Turner">Archie Turner<role>Piano</role></person>
            <person id="M Allen">Michael Allen<role>Piano</role></person>
            <person id="B Gibb">Barry Gibb <role>Writer</role></person>
            <person id="R Gibb">Robin Gibb <role>Writer</role></person>
            <person id="N Whitfield">Norman Whitfield <role>Writer</role></person>
            <person id="B Strong">Barrett Strong</person>
            <!-- The Gibbs, Whitfield, and Strong are not listed anywhere else on the cover. I've found the infor myself and included it in the provenance field because this is potentially important metadata -->
            <organization id="MemphisStrings">The Memphis Strings <role>Strings
                Section</role></organization>
        </creators>
    </provenance>
    <recording/>
    <sleeve>
        <frontcover/>
        <backcover text="white">
            <!-- I put text color here on the assumption that it would apply to all child elements. Is this the correct way to do this? -->
            <sidebar location="left" orientation="bottom-top">Al Green's Greatest Hits
                    <specialcharacter id="qcqc" href="/z656/assignment1/qcqc.PNG"/><specialcharacter
                    id="DVD Audio" href="/z656/assignment1/DVD-Audio_Logo.svg"/><specialcharacter
                    id="MLP Losless" href="/z656/assignment1/Dolby_MLP.svg"/><specialcharacter
                    id="Dolby Digital" href="/z656/assignment1/Dolby-Digital.svg"/><specialcharacter
                    id="dts" href="/z656/assignment1/dts-digital-sound-logo.jpg"/><specialcharacter
                    id="DVD Video" href="/z656/assignment1/Dvd-video-logo.svg"/></sidebar>
            <sidebar location="right" orientation="top-bottom">Al Green's Greatest Hits
                    <specialcharacter id="qcqc" href="/z656/assignment1/qcqc.PNG"/><specialcharacter
                    id="DVD Audio" href="/z656/assignment1/DVD-Audio_Logo.svg"/><specialcharacter
                    id="MLP Losless" href="/z656/assignment1/Dolby_MLP.svg"/><specialcharacter
                    id="Dolby Digital" href="/z656/assignment1/Dolby-Digital.svg"/><specialcharacter
                    id="dts" href="/z656/assignment1/dts-digital-sound-logo.jpg"/><specialcharacter
                    id="DVD Video" href="/z656/assignment1/Dvd-video-logo.svg"/></sidebar>
            <!-- I have no idea what the qcqc icon is, and google isn't any help. I've included a cropped image because it is likely the closest I can come. I also couldn't find the exact dts-digital logo, so this one is close. All images are from wikipedia -->
            <tracklist location="top" alignment="left">
                <!-- I didn't include any content in the most of the person elements here (except those which had a different presentation
 than in the provenance section), figuring that a transformation could take care of that. Should I have included contents in these elements? -->
                <song track="T01">
                    <title>TIRED OF BEING ALONE</title>
                    <songcredits >(<person id="A Green"/>)<label id="BMI"/></songcredits>
                </song>
                <song track="T02">
                    <title>CALL ME (COME BACK HOME)</title>
                    <songcredits >(<person id="A Green"/>;<person id="W Mitchell"/>;<person
                            id="A Jackson"/>)<label id="BMI"/></songcredits>
                </song>
                <song track="T03">
                    <title>I'M STILL IN LOVE WITH YOU</title>
                    <songcredits >(<person id="A Green"/>;<person id="W Mitchell"/>;<person
                            id="A Jackson"/>)<label id="BMI"/></songcredits>
                </song>
                <song track="T04">
                    <title>HERE I AM (COME AND TAKE ME)</title>
                    <songcredits >(<person id="A Green"/>;<person id="T Hodges">M
                            Hodges</person>)<label id="BMI"/></songcredits>
                </song>
                <!-- Teenie Hodges is listed as M Hodges here, but I'm not sure what the best way to represent that difference in xml. I assumed making M Hodges the content of the element would do this, and I did the same thing below iwth Whitfield and Strong -->
                <song track="T05">
                    <title>HOW CAN YOU MEND A BROKEN HEART</title>
                    <songcredits >(<person id="B Gibb"/>;<person id="R Gibb"/>)<label
                            id="BMI"/></songcredits>
                </song>
                <song track="T06">
                    <title>LET'S STAY TOGETHER</title>
                    <songcredits >(<person id="A Green"/>;<person id="W Mitchell"/>;<person
                            id="A Jackson"/>)<label id="BMI"/></songcredits>
                </song>
                <song track="T07">
                    <title>I CAN'T GET NEXT TO YOU</title>
                    <songcredits >(<person id="N Whitfield">Whitfield</person>;<person
                            id="B Strong">Strong</person>)<label id="ASCAP"/></songcredits>
                </song>
                <song track="T08">
                    <title>YOU OUGHT TO BE WITH ME</title>
                    <songcredits >(<person id="A Green"/>;<person id="W Mitchell"/>;<person
                            id="A Jackson"/>)<label id="BMI"/></songcredits>
                </song>
                <song track="T09">
                    <title>LOOK WHAT YOU DONE FOR ME</title>
                    <songcredits >(<person id="A Green"/>;<person id="W Mitchell"/>;<person
                            id="A Jackson"/>)<label id="BMI"/></songcredits>
                </song>
                <song track="T10">
                    <title>LET'S GET MARRIED</title>
                    <songcredits >(<person id="A Green"/>)<label id="BMI"/></songcredits>
                </song>
            </tracklist>
            <albumcredits location="top" alignment="right">
                <producers>Producers:<person id="W Mitchel"/> and <person id="A Green"/></producers>
                <engineers>Engineer:<person id="W Mitchell"/></engineers>
                <remix>Remix Engineer:<person id="W Mitchell"/></remix>
                <vocalbackgrounds>Vocal Backgrounds:<person id="Rhodes1"/>,<person id="C Chalmers"/>
                    and <person id="Rhodes2"/></vocalbackgrounds>
                <stringarrangement>String Arramgements:<person id="J Mitchel"/> and <person
                        id="C Chalmers"/></stringarrangement>
                <!-- Typo "String arramgements in the original -->
                <strings>String Section: <organization id="MemphisStrings"/></strings>
                <horns>Horn Section: <person id="W Jackson"/>-Trumpet; <person id="A Love"/>-Tenor;
                        <person id="E Logan"/>-Tenor; <person id="J Mitchell"/>- Baritone Sax;
                        <person id="J Hole"/>-Trombone</horns>
                <rhythm>Rhythm Section: <person id="H Grimes"/>, <person id="A Jackson"/>- Drums,
                    Conga, &amp; Bongo; <person id="L Hodges"/>-Bass; <person id="C Hodges"/>- Organ
                    and Piano; <person id="T Hodges"/>-Guitar; <person id="A turner"/> &amp;<person
                        id="M Allen"/>-Piano</rhythm>
                <location>Recorded at <reclocation id="RRC"/></location>
            </albumcredits>
            <background>
