=== dmgustav/dmgustav.github.io/z656/assignment3/recipeml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="ingredient"><xs:complexType mixed="true">
        <xs:all>
            <xs:element name="quantity">
                <xs:complexType>
                    <xs:attribute name="unit"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="kind">
                <xs:complexType>
                    <xs:attribute name="preperation"/>
                    <xs:attribute name="brand"/>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
        
    </xs:element>
<xs:element name="recipe">
    <xs:complexType>
        <xs:sequence>
           <xs:element name="supplies">
               <xs:complexType>
                   <xs:all>
                       <xs:element ref="ingredient" minOccurs="1"/>
                   </xs:all>
               </xs:complexType>
           </xs:element> 
            <xs:element name="directions" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="step">
                            <xs:complexType mixed="true">
                                <xs:sequence>
                                    <xs:element ref="ingredient"/>
                                    <xs:element name="cookware">
                                        <xs:complexType>
                                            <xs:attribute name="dimensions"/>
                                            <xs:attribute name="units"/>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="substep">
                                        <xs:complexType><xs:sequence><xs:element ref="ingredient"/></xs:sequence>
                                        <xs:attribute name="action"/>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="temp">
                                        <xs:complexType>
                                            <xs:attribute name="units"/>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="durration">
                                        <xs:complexType>
                                            <xs:attribute name="units"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="action"/>
                                <xs:attribute name="appliance"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== dmgustav/dmgustav.github.io/z656/assignment3/frenchcranberry.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="recipeml.xsd">
    <name>French Cranberry Chicken</name>
    <supplies>
        <ingredient id="1">
            <quantity unit="cup">1</quantity>
            <kind preparation="prepared" brand="Soup of Success">French Cr√©me dressing</kind>
        </ingredient>
        <ingredient id="2">
            <quantity unit="cup">1</quantity>
            <kind preparation="whole">cranberry sauce</kind>
        </ingredient>
        <ingredient id="3">
            <quantity unit="package">1</quantity>
            <kind preparation="dry">onion soup mix</kind>
        </ingredient>
        <ingredient id="4">
            <quantity unit="pounds">1.5</quantity>
            <kind preparation="de-boned" cut="breast">chicken</kind>
        </ingredient>
        <ingredient id="5" appearance="hidden">
            <kind>rice</kind>
            <quantity unit="serving">1</quantity>
        </ingredient>
        <!-- Rice is included in the directions, but not the ingredient list. I considered including it here and commenting it out, but that would make non-computer readable. I decided to instead give this ingredient the attribute "hidden" to show that it would not be included in the printed ingredient list, but to hopefully make it still useful for Alexa as she attempts to prepare dinner (of course, any IOT device would probably want a qantity as well, and the steps below would likely need much more information to make them useful for a computer) -->
    </supplies>
    <directions>
        <step action="place">Place <ingredient id="4">chicken</ingredient> in a <cookware dimensions="9x13" units="inches">dish</cookware></step>
        <step>
            <sub-step action="mix">Mix <ingredient id="1">dressing</ingredient>, <ingredient id="2">cranberry sauce</ingredient>, and <ingredient id="3">soup
                mix</ingredient></sub-step>
            <sub-step action="pour">pour over <ingredient id="4">chicken</ingredient></sub-step>
        </step>
        <step action="bake" appliance="oven">Bake at <temp units="degrees">350 degrees</temp> for
                <duration unit="minutes">45 minutes</duration></step>
        <step action="serve">Serve over <ingredient id="5">rice</ingredient> and enjoy</step>
    </directions>
</recipe>
